# Generated by Django 5.2.6 on 2025-10-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_total_price_alter_address_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cutomer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dicount_code',
            new_name='discount_code',
        ),
    ]
