# Generated by Django 5.2.6 on 2025-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_cutomer_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='dicount_price',
            new_name='discount_price',
        ),
    ]
