# Generated by Django 5.2.7 on 2025-10-18 14:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_dicount_price_orderitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
